// source: general.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

var landing_pb = require('./landing_pb.js');
goog.object.extend(proto, landing_pb);
var takeoff_pb = require('./takeoff_pb.js');
goog.object.extend(proto, takeoff_pb);
goog.exportSymbol('proto.general.Request', null, global);
goog.exportSymbol('proto.general.Response', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.general.Request = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.general.Request, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.general.Request.displayName = 'proto.general.Request';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.general.Response = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.general.Response, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.general.Response.displayName = 'proto.general.Response';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.general.Request.prototype.toObject = function(opt_includeInstance) {
  return proto.general.Request.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.general.Request} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.general.Request.toObject = function(includeInstance, msg) {
  var f, obj = {
    landingreq: (f = msg.getLandingreq()) && landing_pb.LandingRequest.toObject(includeInstance, f),
    takeoffreq: (f = msg.getTakeoffreq()) && takeoff_pb.TakeoffRequest.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.general.Request}
 */
proto.general.Request.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.general.Request;
  return proto.general.Request.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.general.Request} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.general.Request}
 */
proto.general.Request.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new landing_pb.LandingRequest;
      reader.readMessage(value,landing_pb.LandingRequest.deserializeBinaryFromReader);
      msg.setLandingreq(value);
      break;
    case 2:
      var value = new takeoff_pb.TakeoffRequest;
      reader.readMessage(value,takeoff_pb.TakeoffRequest.deserializeBinaryFromReader);
      msg.setTakeoffreq(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.general.Request.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.general.Request.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.general.Request} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.general.Request.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getLandingreq();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      landing_pb.LandingRequest.serializeBinaryToWriter
    );
  }
  f = message.getTakeoffreq();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      takeoff_pb.TakeoffRequest.serializeBinaryToWriter
    );
  }
};


/**
 * optional landing.LandingRequest landingReq = 1;
 * @return {?proto.landing.LandingRequest}
 */
proto.general.Request.prototype.getLandingreq = function() {
  return /** @type{?proto.landing.LandingRequest} */ (
    jspb.Message.getWrapperField(this, landing_pb.LandingRequest, 1));
};


/**
 * @param {?proto.landing.LandingRequest|undefined} value
 * @return {!proto.general.Request} returns this
*/
proto.general.Request.prototype.setLandingreq = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.general.Request} returns this
 */
proto.general.Request.prototype.clearLandingreq = function() {
  return this.setLandingreq(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.general.Request.prototype.hasLandingreq = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional takeoff.TakeoffRequest takeoffReq = 2;
 * @return {?proto.takeoff.TakeoffRequest}
 */
proto.general.Request.prototype.getTakeoffreq = function() {
  return /** @type{?proto.takeoff.TakeoffRequest} */ (
    jspb.Message.getWrapperField(this, takeoff_pb.TakeoffRequest, 2));
};


/**
 * @param {?proto.takeoff.TakeoffRequest|undefined} value
 * @return {!proto.general.Request} returns this
*/
proto.general.Request.prototype.setTakeoffreq = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.general.Request} returns this
 */
proto.general.Request.prototype.clearTakeoffreq = function() {
  return this.setTakeoffreq(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.general.Request.prototype.hasTakeoffreq = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.general.Response.prototype.toObject = function(opt_includeInstance) {
  return proto.general.Response.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.general.Response} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.general.Response.toObject = function(includeInstance, msg) {
  var f, obj = {
    landingresp: (f = msg.getLandingresp()) && landing_pb.LandingResponse.toObject(includeInstance, f),
    takeoffresp: (f = msg.getTakeoffresp()) && takeoff_pb.TakeoffResponse.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.general.Response}
 */
proto.general.Response.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.general.Response;
  return proto.general.Response.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.general.Response} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.general.Response}
 */
proto.general.Response.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new landing_pb.LandingResponse;
      reader.readMessage(value,landing_pb.LandingResponse.deserializeBinaryFromReader);
      msg.setLandingresp(value);
      break;
    case 2:
      var value = new takeoff_pb.TakeoffResponse;
      reader.readMessage(value,takeoff_pb.TakeoffResponse.deserializeBinaryFromReader);
      msg.setTakeoffresp(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.general.Response.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.general.Response.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.general.Response} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.general.Response.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getLandingresp();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      landing_pb.LandingResponse.serializeBinaryToWriter
    );
  }
  f = message.getTakeoffresp();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      takeoff_pb.TakeoffResponse.serializeBinaryToWriter
    );
  }
};


/**
 * optional landing.LandingResponse landingResp = 1;
 * @return {?proto.landing.LandingResponse}
 */
proto.general.Response.prototype.getLandingresp = function() {
  return /** @type{?proto.landing.LandingResponse} */ (
    jspb.Message.getWrapperField(this, landing_pb.LandingResponse, 1));
};


/**
 * @param {?proto.landing.LandingResponse|undefined} value
 * @return {!proto.general.Response} returns this
*/
proto.general.Response.prototype.setLandingresp = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.general.Response} returns this
 */
proto.general.Response.prototype.clearLandingresp = function() {
  return this.setLandingresp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.general.Response.prototype.hasLandingresp = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional takeoff.TakeoffResponse takeoffResp = 2;
 * @return {?proto.takeoff.TakeoffResponse}
 */
proto.general.Response.prototype.getTakeoffresp = function() {
  return /** @type{?proto.takeoff.TakeoffResponse} */ (
    jspb.Message.getWrapperField(this, takeoff_pb.TakeoffResponse, 2));
};


/**
 * @param {?proto.takeoff.TakeoffResponse|undefined} value
 * @return {!proto.general.Response} returns this
*/
proto.general.Response.prototype.setTakeoffresp = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.general.Response} returns this
 */
proto.general.Response.prototype.clearTakeoffresp = function() {
  return this.setTakeoffresp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.general.Response.prototype.hasTakeoffresp = function() {
  return jspb.Message.getField(this, 2) != null;
};


goog.object.extend(exports, proto.general);
